interface WordSet {
	categories: {
		[key: string]: {
			displayName: string;
			values: string[];
		};
	};
}

const wordset: WordSet = {
	categories: {
		travel: {
			displayName: "Travel",
			values: [
				"plane",
				"boat",
				"geography",
				"baggage",
				"guide",
				"sea",
				"air",
				"land",
				"holiday",
				"bus",
				"explore",
				"adventure",
				"expenses",
				"pictures",
				"excitement",
			],
		},
		classroom: {
			displayName: "Classroom",
			values: [
				"whiteboard",
				"marker",
				"crayon",
				"pencil",
				"rubber",
				"pen",
				"duster",
				"poster",
				"diagram",
				"apple",
				"colours",
				"mat",
				"books",
				"smartboard",
				"koki",
				"math",
				"english",
				"inclusive",
				"science",
				"play",
				"stickers",
				"highlighter",
				"desk",
				"chair",
			],
		},
		ice_cream: {
			displayName: "Ice Cream",
			values: [
				"chocolate",
				"brownie",
				"vanilla",
				"strawberry",
				"rockyroad",
				"custard",
				"birthday",
				"orange",
				"whitechoc",
				"rumraisin",
				"pecan",
				"cremesoda",
				"cashew",
				"pistachio",
				"amarula",
				"vegan",
				"chocchip",
			],
		},
		hobbies: {
			displayName: "Hobbies",
			values: [
				"swimming",
				"knitting",
				"writing",
				"cubing",
				"coding",
				"drawing",
				"jogging",
				"baking",
				"cooking",
				"videos",
				"decorating",
				"movies",
				"eating",
				"reading",
				"walking",
				"shopping",
				"organizing",
				"driving",
				"hunting",
				"farming",
				"journalling",
				"singing",
			],
		},
		space: {
			displayName: "Space",
			values: [
				"earth",
				"planets",
				"mars",
				"venus",
				"jupiter",
				"asteroid",
				"satellite",
				"spacesuit",
				"astronaut",
				"rocket",
				"comet",
				"science",
				"moon",
				"landing",
				"rover",
				"space",
				"aliens",
				"exploration",
			],
		},
		mathematics: {
			displayName: "Math",
			values: [
				"integral",
				"differentiate",
				"algorithm",
				"calculus",
				"algebra",
				"equation",
				"symbol",
				"pi",
				"equal",
				"square",
				"circumference",
				"problem",
				"graph",
				"calculator",
				"proof",
				"statistics",
				"power",
			],
		},
		lifestyle: {
			displayName: "Lifestyle",
			values: [
				"active",
				"simple",
				"luxury",
				"adventure",
				"responsible",
				"quiet",
				"city",
				"rural",
				"solo",
				"bohemian",
				"hippie",
				"dependent",
				"homey",
				"country",
				"inactive",
				"lazy",
			],
		},
		foods: {
			displayName: "Foods",
			values: [
				"sushi",
				"tacos",
				"pizza",
				"boerewors",
				"pap",
				"burger",
				"fries",
				"hashbrowns",
				"relish",
				"salad",
				"steak",
				"rice",
				"chicken",
				"lettuce",
				"mayonnaise",
				"jam",
				"nachos",
				"wings",
				"poppers",
				"snails",
				"crab",
				"ketchup",
			],
		},
	},
};

export default wordset;
